version: "3.9"

services:
  lb:
    image: "shijialee/load_balancer:88d35b073ec3"
    ports:
      - "80:80"
    networks:
      - laravel_test_app
    depends_on:
      - php-fpm
    volumes:
      - type: bind
        source: ./vhost.conf
        target: /etc/nginx/conf.d/vhost.conf
      - type: bind
        source: /vagrant/www/laravel_test/test/public
        target: /var/www/laravel_test/test/public
    environment:
      NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE: 1
  php-fpm:
    image: "shijialee/phpfpm:39e96564a5ca"
    networks:
      - laravel_test_app
    volumes:
      - type: bind
        source: ${APP_ROOT:?}
        target: /var/www

networks:
  laravel_test_app:
