version: "3.9"

services:
  lb:
    image: "shijialee/load_balancer:88d35b073ec3"
    ports:
      - "80:80"
    networks:
      - laravel_test_app
    depends_on:
      - php-fpm
      - redis
      - db
    volumes:
      - type: bind
        source: ./vhost.conf
        target: /etc/nginx/conf.d/vhost.conf
      - type: bind
        source: /vagrant/www/laravel_test/test/public
        target: /var/www/laravel_test/test/public
    environment:
      NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE: 1
  php-fpm:
    image: "shijialee/phpfpm:39e96564a5ca"
    networks:
      - laravel_test_app
    volumes:
      - type: bind
        source: ${APP_ROOT:?}
        target: /var/www
  redis:
    image: "redis:6.2.1-buster"
    networks:
      - laravel_test_app
    volumes:
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  db:
    image: "mysql:5.7.33"
    networks:
      - laravel_test_app
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_DATABASE=laravel_test
      - MYSQL_USER=laravel_test
      - MYSQL_PASSWORD=laravel_test
    volumes:
      - type: volume
        source: laravel-test-db-data
        target: /var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'

networks:
  laravel_test_app:

volumes:
  laravel-test-db-data:
